version: 2
jobs:
  test1:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "nginx-review"
    steps:
      - checkout
      - run:
          name: test1
          command: |
            echo "test1"
      - setup_remote_docker
  test2:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "nginx-review"
    steps:
      - checkout
      - run:
          name: test2
          command: |
            echo "test2"
      - setup_remote_docker
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test1
