version: 2
gcp-build-deploy: &gcp-build-deploy
  docker:
    - image: google/cloud-sdk:311.0.0-slim
  steps:
    - checkout
    - run:
        name: Setup Google Cloud SDK
        command: |
          apt-get install -qq -y gettext
          echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_REGION}-a
          gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME} --zone ${GOOGLE_COMPUTE_REGION}-c
    - setup_remote_docker
    - run: 
        name: Review docker build and push
        command: |
          cd ${HOME}/sample-app/Dockerfile
          docker build -t gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}-img:${CIRCLE_SHA1} .
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
          docker push gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}-img:${CIRCLE_SHA1}
    - run: 
        name: Deploy application to Kubernetes
        command: |
          envsubst < ${HOME}/sample-app/kubernetes/${FILE_NAME}.yml > ${HOME}/patched-config.yml
          kubectl apply -f ${HOME}/patched-config.yml
          if [[ ${PROJECT_NAME} == "nginx-review" ]]; then
            kubectl rollout status deployment/${PROJECT_NAME}-${PR_NUMBER}-deployment -n ${PROJECT_NAME}-${PR_NUMBER}-ns
          else
            kubectl rollout status deployment/${PROJECT_NAME}-deployment -n ${PROJECT_NAME}-ns
          fi
jobs:
  review_deploy:
    <<: *gcp-build-deploy
    environment:
      - PROJECT_NAME: "nginx-review"
      - FILE_NAME: "review-config.yml"
  stage_deploy:
    <<: *gcp-build-deploy
    environment:
      - PROJECT_NAME: "nginx-stage"
      - FILE_NAME: "stage-config.yml"
  prod_deploy:
    <<: *gcp-build-deploy
    environment:
      - PROJECT_NAME: "nginx-prod"
      - FILE_NAME: "prod-config.yml"
  review_remove:
    docker:
      - image: google/cloud-sdk:311.0.0-slim
    environment:
      - PROJECT_NAME: "nginx-review"
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_REGION}-a
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME} --zone ${GOOGLE_COMPUTE_REGION}-c
      - setup_remote_docker
      - run: 
          name: Remove review application from Kubernetes
          command: |
            if [[ $(kubectl get namespace ${PROJECT_NAME}-${PR_NUMBER}-ns) ]]; then
                kubectl delete namespace ${PROJECT_NAME}-${PR_NUMBER}-ns
            fi
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - prod_deploy:
          filters:
            branches:
              only:
                - master
      - stage_deploy:
          filters:
            branches:
              only: 
                - stage
