# Author: Anil Saravade
# Copyright: Copyright (©) 2020. SwapStyle. All rights reserved.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-sa
  namespace: webhook-ns
  labels:
    app: webhook