# Author: Anil Saravade
# Copyright: Copyright (©) 2020. SwapStyle. All rights reserved.

apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: webhook-cert
  namespace: webhook-ns
  labels:
    app: webhook
spec:
  domains:
    - webhook.[DNS_NAME]