# Author: Anil Saravade
# Copyright: Copyright (©) 2020. SwapStyle. All rights reserved.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-role
  namespace: webhook-ns
  labels:
    app: webhook
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]