# Author: Anil Saravade
# Copyright: Copyright (©) 2020. SwapStyle. All rights reserved.

apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: webhook-ns
  labels:
    app: webhook
type: Opaque
data:
  WEBHOOK_VERIFY_TOKEN: XXXXXX
  CIRCLE_API_USER_TOKEN: XXXXXX
  CIRCLE_URL: XXXXXX
  CIRCLE_DEPLOY_JOB: XXXXXX
  CIRCLE_REMOVE_JOB: XXXXXX